version: "3"
services:
  oracle-xe:
    image: gvenzl/oracle-xe:18.4.0-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"   # SQL*Net Listener
      - "5500:5500"   # Enterprise Manager Express (optional)
    environment:
      ORACLE_PASSWORD: YourStrongPassword123
      APP_USER: appuser
      APP_USER_PASSWORD: AppUserPassword123
    restart: always

